version: "3.9"
services:
  app:
    image: telegram-bot-bash:latest
    restart: always
    user: botbash
    command: >
      bash -l -c "/app/bashbot.sh start
      && tail -f /dev/null"
    volumes:
      - type: bind
        source: ./botconfig.jssh
        target: /app/botconfig.jssh
      - type: bind
        source: ./botacl
        target: /app/botacl
      - type: bind
        source: ./mycommands.conf
        target: /app/mycommands.conf
      - type: bind
        source: ./mycommands.sh
        target: /app/mycommands.sh
      - type: bind
        source: ./logs
        target: /app/logs
